<?php

namespace Tarosky\MakePostmetaFaster;


use Tarosky\MakePostmetaFaster\Pattern\SingletonPattern;

/**
 * Add setting screen.
 */
class Setting extends SingletonPattern {

	/**
	 * {@inheritDoc}
	 */
	protected function init() {
		parent::init(); // TODO: Change the autogenerated stub
	}


}
