name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Build and attach zip
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/releases
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-dev

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: |
          npm run build:js
          npm run build:css
          npm run dump

      - name: Versioning
        uses: tarosky/workflows/actions/versioning@main
        with:
          version: ${{ github.event.release.tag_name }}
          files: make-postmeta-faster.php

      - name: Clean Package
        uses: tarosky/workflows/actions/distignore@main

      - name: Zip Archive
        run: |
          mkdir ${{ github.event.repository.name }}
          rsync -av --exclude=${{ github.event.repository.name }} --exclude=.git ./ ./${{ github.event.repository.name }}/
          zip -r ./${{ github.event.repository.name }}.zip ./${{ github.event.repository.name }}

      - name: Upload release asset
        run: gh release upload ${{ github.event.release.tag_name }} ${{ github.workspace }}/${{ github.event.repository.name }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
