name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://wordpress.org/plugins/make-postmeta-faster/
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-dev

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: |
          npm run build:js
          npm run build:css
          npm run dump

      - name: Generate readme.txt
        uses: tarosky/workflows/actions/wp-readme@main

      - name: Versioning
        uses: tarosky/workflows/actions/versioning@main
        with:
          version: ${{ github.event.release.tag_name }}
          files: make-postmeta-faster.php

      - name: Deploy to WordPress Directory
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SLUG: make-postmeta-faster
          SVN_USERNAME: ${{ secrets.WP_ORG_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WP_ORG_PASSWORD }}

      - name: Upload release asset
        run: gh release upload ${{ github.event.release.tag_name }} ${{ github.workspace }}/${{ github.event.repository.name }}.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
